In [3]:
import numpy as np    #numpy is a package for scientific computing
from collections import Counter
vocab = Counter()
text = "Hi from Brazil"
#Get all words
for word in text.split(' '):
    vocab[word]+=1
        
#Convert words to indexes
def get_word_2_index(vocab):
    word2index = {}
    for i,word in enumerate(vocab):
        word2index[word] = i
        
    return word2index
#Now we have an index
word2index = get_word_2_index(vocab)
total_words = len(vocab)
#This is how we create a numpy array (our matrix)
matrix = np.zeros((total_words),dtype=float)
#Now we fill the values
for word in text.split():
    matrix[word2index[word]] += 1
print(matrix)

[1. 1. 1.]


In [4]:
matrix = np.zeros((total_words),dtype=float)
text = "Hi"
print(matrix)
for word in text.split():
    matrix[word2index[word]] += 1
print(matrix)
#for word in text.split():
    #print(word)
    #print(matrix)
    #print(word2index[word])
    #matrix[get_word_2_index[word]] += 1
#print(matrix)

[0. 0. 0.]
[1. 0. 0.]


In [5]:
category=0;
y = np.zeros((3),dtype=float)
if category == 0:
    y[0] = 1.        # [ 1.  0.  0.]
elif category == 1:
    y[1] = 1.        # [ 0.  1.  0.]
else:
     y[2] = 1.       # [ 0.  0.  1.]

In [6]:
from sklearn.datasets import fetch_20newsgroups
categories = ["comp.graphics","sci.space","rec.sport.baseball"]
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories)
newsgroups_test = fetch_20newsgroups(subset='test', categories=categories)

In [14]:
type(newsgroups_train)

sklearn.utils._bunch.Bunch

In [1]:
import tensorflow as tf

2023-10-24 15:43:06.455151: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [8]:
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior()
n_input = total_words # Words in vocab
n_classes = 3         # Categories: graphics, sci.space and baseball
input_tensor = tf.placeholder(tf.float32,[None, n_input],name="input")
output_tensor = tf.placeholder(tf.float32,[None, n_classes],name="output")

Instructions for updating:
non-resource variables are not supported in the long term


In [21]:
len(newsgroups_train.data)
type(newsgroups_train.data)
data(newsgroups_train.data

list

In [20]:
def get_batch(data, batch_num, batch_size):
    start_idx = batch_num * batch_size
    end_idx = (batch_num + 1) * batch_size
    batch_x = data[start_idx:end_idx] 
    batch_y = labels[start_idx:end_idx]  # Modify based on your data structure

    return batch_x, batch_y

batch_size=500;
training_epochs = 10
# Launch the graph
with tf.Session() as sess:
    init=tf.compat.v1.global_variables_initializer();
    sess.run(init) #inits the variables (normal distribution, remember?)
    # Training cycle
    for epoch in range(training_epochs):
        avg_cost = 0.
        total_batch = int(len(newsgroups_train.data)/batch_size)
        # Loop over all batches
        for i in range(total_batch):
            batch_x,batch_y = get_batch(newsgroups_train,i,batch_size)
            # Run optimization op (backprop) and cost op (to get loss value)
            c,_ = sess.run([loss,optimizer], feed_dict={input_tensor: batch_x, output_tensor:batch_y})

TypeError: unhashable type: 'slice'